### ISSUE TITLE
[php] First letter after backslash is treated like an escape sequence in single quoted strings

### ISSUE THREAD

**Issue by Sobak** [kadet1090/KeyLighter#1]
I think that snippet makes it obvious

Snippet with error: [#571a31319d764](http://keylighter.kadet.net/snippet/571a31319d764)
Language: php `Kadet\Highlighter\Language\Php`
Version: 0.8.0-1e4513b

**Comment by kadet1090** [comment]
It's correct behavior for double quoted strings, where every character after \ is treated like escape sequence (\n, \r etc.), in single quoted strings only \\ and \' are valid escapes, i'll try to somehow separate them.
