### ISSUE TITLE
Is there a reason why you required symfony/console 3.1 and not 2.8?

### ISSUE THREAD

**Issue by marcj** [kadet1090/KeyLighter#2]
Would be great to support 2.8 as well. I don't see on a quick look why you enforce `3.1`.

**Comment by marcj** [comment]
Is it maybe possible to extract the actual binary application stuff (command line interface) to an separate package? I actually only need your php classes, not your console application.

**Comment by kadet1090** [comment]
I encountered that conflict too, I will try to lower it to 2.8 and mark it as non required dependency. I don't remember why it was set to 3.1, maybe I was testing something from symfony 3 and haven't checked if actual version runs well on 2.8. Thx for reporting
